### ISSUE TITLE
Rename after link creates different directory structure than os

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#227]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "b" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
component0 = "gamma" 
path0 = path0 + "/" + component0 
os0.mkdir(path0) 
path0 = path0 + "/" + component0 
fd0 = os0.open(path0, os.O_CREAT | os.O_WRONLY | os.O_TRUNC)  
os0.link(path0,path1) 
os0.rename(path0,path1) 
path0 = "/Volumes/ramdisk/test" 
result = [p for p in os0.walk(path0,topdown=True,followlinks=True)]

print result

pyfakefs gets:

[('/Volumes/ramdisk/test', ['gamma'], ['b']), ('/Volumes/ramdisk/test/gamma', [], [])]

vs. os:

[('/Volumes/ramdisk/test', ['gamma'], ['b']), ('/Volumes/ramdisk/test/gamma', [], ['gamma'])]

**Comment by mrbean-bremen** [comment]
Another rename problem... this turned out to be more complicated than I thought. We already raise 8 different types of OSError in rename (as the behavior also differs between Windows and Posix).

The (real os) behavior described in this issue is somewhat surprising to me. If you rename a hard link to a file it is pointing to (or more accurately, another representation of the same file), both hard links remain, but with the same name. I wouldn't have expected this.

**Comment by agroce** [comment]
Is this actually what POSIX wants?  If I read right, C rename just terminates if src and dst are hard links to same file (http://man7.org/linux/man-pages/man2/rename.2.html)

**Comment by mrbean-bremen** [comment]
You are right - I seem to have messed up the test.
