### ISSUE TITLE
Rename succeeds when should fail

### ISSUE THREAD

**Issue by agroce** [jmcgeheeiv/pyfakefs#232]
import pyfakefs.fake_filesystem
import os

fs = pyfakefs.fake_filesystem.FakeFilesystem()
fs.CreateDirectory('/Volumes')	
fs.CreateDirectory('/Volumes/ramdisk')
fs.CreateDirectory('/Volumes/ramdisk/test')
os0 = pyfakefs.fake_filesystem.FakeOsModule(fs)

component0 = "b" 
component1 = "c" 
path0 = "/Volumes/ramdisk/test" 
path1 = path0 + "/" + component0 
component0 = "alpha" 
path0 = path1 + "/" + component0 
component0 = "e" 
path1 = path0 + "/" + component1 
path0 = path1 + "/" + component1 
path1 = path1 + "/" + component0 
os0.makedirs(path0) 
fd0 = os0.open(path1, os.O_CREAT | os.O_WRONLY | os.O_TRUNC) 
os0.rename(path0,path1) 

The rename succeeds, but os fails with exception:

Traceback (most recent call last):
  File "bug19.py", line 29, in <module>
    os0.rename(path0,path1) 
OSError: [Errno 20] Not a directory

**Comment by mrbean-bremen** [comment]
I will check this one next weekend (won't have time before that), but I don't expect this to be a big issue.

**Comment by agroce** [comment]
Yeah, I suspect it's just changing some guard to match POSIX a little better, boring stuff.  I'll see if I can find a hack guard to avoid the known symlink problem, but might be easier to just hold on symlink until it's "roughly working" if you think it's just broken right now.

**Comment by mrbean-bremen** [comment]
I think it's less broken thhan I thought, though it could be implemeneted nicer. I don't know if you can work around the known problem with `walk` (I don't know yet how to handle that), but I think it makes sense to test some more symlink stuff.

**Comment by agroce** [comment]
Ok, I added a feature to TSTL to generate automatic checks for same exception (either exact message match) or type match.  Let me know if you want to see the cases where you raise OSError vs IOError for os, etc.  There may be quite a few of these, and they are not exciting, but they're easy to find (and probably to fix).

**Comment by mrbean-bremen** [comment]
Well, as you said,  it's not exciting, but needed anyway, at least in Python 2. Thankfully, in Python  3 `IOError` is just an alias to `OSError`, while in Python 2 the usage seems to be inconsistent. There is also the problem, that under Windows often  (but not always) `WinError` is raised instead of `IOError`, which is derived from `OSError`, meaning that code that catches one of `IOError` or `OSError` is not compatible between Windows and Posix systems. Anyway, this may be a good opportunity to fix some of the incorrect exceptions.
