### ISSUE TITLE
Remove support for Python 2.6

### ISSUE THREAD

**Issue by mrbean-bremen** [jmcgeheeiv/pyfakefs#293]
With Python 2.6 being at end of life now almost 4 years, we may drop the support IMHO. 
Most other packages are also dropping support, so there is not much sense to keep it. 
This will also allow to to cleanup the code by removing the Python 2.6 specific workarounds.
I propose to do this for the 3.4 release, alongside with the PEP-8 changes.

**Comment by hugovk** [comment]
Drop it and 3.2 as well. Consider dropping 3.3 at the same time, all are EOL. Dropping 3.2 will help get of the strange Unicode handling it requires.

## Reasons for dropping old ones

* https://en.wikipedia.org/wiki/CPython#Version_history

### 2.6

* Unsupported since [2013-10-29](https://en.wikipedia.org/wiki/CPython#Version_history)
* https://snarky.ca/stop-using-python-2-6/
* http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
* http://www.python3statement.org
* Current pip 9 deprecates Python 2.6 support, pip 10 won't support it (https://github.com/pypa/pip/issues/3955)
* Not much PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

### 3.2

* Unsupported since [2016-02-27](https://en.wikipedia.org/wiki/CPython#Version_history)
* pip 8 no longer supports Python 3.2 ([link](https://pip.pypa.io/en/stable/news/))
* Coverage 4 no longer supports Python 3.2 ([link](https://bitbucket.org/ned/coveragepy/issues/407/coverage-failing-on-python-325-using))
* Requests no longer supports Python 3.2
* Virtually no PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

### 3.3

* Unsupported since [2017-09-29](https://en.wikipedia.org/wiki/CPython#Version_history)
* pip 10 will deprecate Python 3.3 support, pip 11 won't support it (https://github.com/pypa/pip/issues/3796)
* Very little PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796

**Comment by mrbean-bremen** [comment]
Right, we already dropped testing 3.2 for that reason some time ago, though it shall still work. We have to update the documentation accordingly.
About 3.3 - unlike in 2.6 and 3.2, there are no language features that are missing or getting in the way, so this can wait.

**Comment by hugovk** [comment]
Yeah, ditching 3.3 isn't so pressing at the moment. There's lots to be gained from dropping 2.6!

**Comment by mrbean-bremen** [comment]
BTW, [here](http://jmcgeheeiv.github.io/pyfakefs/master/intro.html) 3.2 is already not mentioned.
