### ISSUE TITLE
Mock out xattr calls

### ISSUE THREAD

**Issue by dtangster** [jmcgeheeiv/pyfakefs#423]
pyfakefs doesn't seem mock out calls like `os.getxattr`, `os.listxattr`, `os.setxattr`, etc.

Are there plans to support this in the future?

**Comment by mrbean-bremen** [comment]
It has been no need for these so far, it seems, but if needed, we can add support for that, of course.
There is an empty implementation of fake `listxattr`, and we could easily add empty implementations for the rest. The better way is probably to keep track of the extended attributes, defaulting to the attributes not set, so that the user would be responsible to set the attributes in the test setup if needed.

I may have a look at this sometime later - I don't have much free time at the moment.

**Comment by mrbean-bremen** [comment]
@dtangster - can you please check if the implementation in master works for you?

**Comment by mrbean-bremen** [comment]
Closing as fixed with #426 - please reopen if this is not sufficient.
