### ISSUE TITLE
shutil.move() moves directory contents if target dir exists

### ISSUE THREAD

**Issue by FelixSchwarz** [jmcgeheeiv/pyfakefs#515]
I noticed that `shutil.move()` behaves differently if the target directory exists already.

Python:

 - if the target directory exists, move the source directory as a sub-directory of the target dir
 - if target directory does not exist, create it and move only contents of source directory

pyfakefs:

 - always moves contents of source directory only.

I noticed this with Python 2.7 (pyfakefs 3.7.1) and Python 3.8 (latest git, 025f06c).

Related bug was #145 (fixed by e94bb0f55098917f0c093cd952c521e7706db824) but it seems that one missed this edge condition.

Example code:

    #!/usr/bin/env python

    import os
    import shutil
    import tempfile

    USE_PYFAKEFS = False

    if USE_PYFAKEFS:
        from pyfakefs.fake_filesystem_unittest import Patcher
        stubber = Patcher()
        stubber.setUp()

    source_dir = tempfile.mkdtemp()
    target_dir = tempfile.mkdtemp()
    filename = 'foo.pdf'
    with open(os.path.join(source_dir, filename), 'wb') as fp:
        fp.write(b'stub')

    shutil.move(source_dir, target_dir)
    shutil.rmtree(target_dir)

**Comment by mrbean-bremen** [comment]
Thanks! I will try to have a look later tonight.

**Comment by mrbean-bremen** [comment]
Ok, as we do not patch `shutil` functionality, but rely on the native implementation (this has been changed after #145 had been fixed), the real problem seems to be the fake implementation of `os.rename` - this is used by `shutil` and seems to handle this case incorrectly. I will have a go at this somewhere in the next days.

**Comment by mrbean-bremen** [comment]
Ok, turned out to be yet another problem. 

The root cause was that no `st_ino` had been set for the created directory in fake `mkdir`. That let to `os.samefile` not work correctly, as it uses `st_ino` for comparison, e.g. two different newly created directories are seen as the same object. As `os.samefile` is used by `shutil.move` internally, it handled the move as a simple rename.

Thanks for catching this bug!

**Comment by FelixSchwarz** [comment]
Thank you :-)
