### ISSUE TITLE
syntax error in 4.0.2 package

### ISSUE THREAD

**Issue by tswast** [jmcgeheeiv/pyfakefs#525]
**Describe the bug**

When attempting to create a conda package for pyfakefs, I'm getting a syntax error.

```
  Added file://$SRC_DIR to build tracker '/tmp/pip-req-tracker-f5OOUn'
    Running setup.py (path:/tmp/pip-req-build-K9KwEU/setup.py) egg_info for package from file://$SRC_DIR
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-K9KwEU/setup.py", line 22, in <module>
        from pyfakefs.fake_filesystem import __version__
      File "pyfakefs/fake_filesystem.py", line 1195
        def utime(self, path, times=None, *, ns=None, follow_symlinks=True):
                                           ^
    SyntaxError: invalid syntax
```

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=128243&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=419

Is `*` as an argument new syntax? I don't recall seeing it in Python 3.5.

**Your enviroment**

Conda Forge

https://github.com/conda-forge/pyfakefs-feedstock/pull/8

**Comment by mrbean-bremen** [comment]
This has been introduced to several functions in Python 3, the asterisk has been added in Python 3 meaning that all arguments after it are keyword-only arguments. Here is the documentation for [utime](https://docs.python.org/3.5/library/os.html#os.utime).

**Comment by mrbean-bremen** [comment]
The error message looks like it comes from Python 2. I don't know much about conda, and can't have a closer look until later next week (traveling right now).

**Comment by mrbean-bremen** [comment]
Ok, I had a closer look. The problem happens because `setup.py` is loaded by Python 2. `setup.py` takes the version from `fake_filesystem.py`, which is no longer compatible with Python 2. 
So while we could change the implementation to `setup.py` being Python 2 - compatible, the correct fix would be to use Python 3 in the feedstock scripts instead. 
In the [Linux CI configuration file](https://github.com/conda-forge/pyfakefs-feedstock/blob/master/.ci_support/linux_.yaml) Python is currently set to 2.7 - this shall probably changed to Python 3.

**Comment by mrbean-bremen** [comment]
@tswast - can the Python version be changed in the feedstock, or shall I release a new version where `setup.py` can be read by Python 2?

**Comment by tswast** [comment]
Thanks for looking into this. Trying now with an updated "host" python version
